# Generated by Django 4.1.1 on 2022-10-18 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_circle', '0003_profile_circle_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='circles', to='recommendation_circle.profile'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_recommendations', to='recommendation_circle.circle'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='recommendation_circle.circle')),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendation_circle.edition'),
        ),
    ]
