# Generated by Django 4.1.1 on 2022-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_circle', '0004_alter_circle_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='last_edition',
            field=models.IntegerField(default=0),
        ),
    ]
