# Generated by Django 4.1.1 on 2022-10-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_circle', '0005_circle_last_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='circle',
        ),
        migrations.AddField(
            model_name='edition',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_made', to='recommendation_circle.profile'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='recommendation_circle.profile'),
        ),
    ]
